// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0GTdHuDEki9Y8hQN7KLmlhLJ_M1yn2dU',
    appId: '1:1044036493096:web:d658f20181ebb0644b3a1d',
    messagingSenderId: '1044036493096',
    projectId: 'm-link-8ba07',
    authDomain: 'm-link-8ba07.firebaseapp.com',
    storageBucket: 'm-link-8ba07.firebasestorage.app',
    measurementId: 'G-CZ661KYS8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl77vn9EyOgz6bPtMeVbWeqowFMjqdGh8',
    appId: '1:1044036493096:android:8e1540831d84b2f84b3a1d',
    messagingSenderId: '1044036493096',
    projectId: 'm-link-8ba07',
    storageBucket: 'm-link-8ba07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWa5C1i7LhYUNu_wjF-2eWDZFofiVlW3Q',
    appId: '1:1044036493096:ios:394c8a091902ac994b3a1d',
    messagingSenderId: '1044036493096',
    projectId: 'm-link-8ba07',
    storageBucket: 'm-link-8ba07.firebasestorage.app',
    iosBundleId: 'com.example.mLinkProject',
  );

}